version: '3.8'
services:
  client:
    container_name: ampersand-discord-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    pull_policy: build
    restart: unless-stopped
    networks:
      client:
        name: discord
        external: true
    environment:
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_NAME: ${DISCORD_CLIENT_NAME}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_PERMISSION_INTEGER: ${DISCORD_PERMISSION_INTEGER}
      MONGO_URL: ${MONGO_URL}
      LAVALINK_HOST: ${LAVALINK_HOST}
      LAVALINK_PORT: ${LAVALINK_PORT}
      LAVALINK_PASSWORD: ${LAVALINK_PASSWORD}
